### ISSUE TITLE
Issue using action

### ISSUE THREAD

**Issue by Kampe** [toko-bifrost/ms-teams-deploy-card#1]
Tried to use the action, did not publish to teams webhook URI, nothing here telling me what's going on - assuming some assumptions were made around files and repo names being related to a user and not an organization.  

```[@octokit/rest] const Octokit = require("@octokit/rest") is deprecated. Use const { Octokit } = require("@octokit/rest") instead
[@octokit/rest] const Octokit = require("@octokit/rest") is deprecated. Use const { Octokit } = require("@octokit/rest") instead
(node:3946) UnhandledPromiseRejectionWarning: HttpError: Not Found
    at /home/runner/work/_actions/toko-bifrost/ms-teams-deploy-card/1.0.0/dist/index.js:8725:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async run (/home/runner/work/_actions/toko-bifrost/ms-teams-deploy-card/1.0.0/dist/index.js:8515:20)
(node:3946) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3946) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aldwyn-acn** [comment]
Hi @Kampe,

What version did you use? You should use toko-bifrost/ms-teams-deploy-card@2.0.0. I will update the README. Let me know if it resolved your problem.

Thanks for bringing this to my attention.

**Comment by aldwyn-acn** [comment]
Hi @Kampe, I'm closing this issue. Kindly reopen this if you still have concerns.

**Comment by Kampe** [comment]
This is still an issue, I was using 1.0.0, now with 2.0.0 I'm getting invalid credentials errors. Using this yaml
```
    - name: Notify dedicated teams channel
      uses: toko-bifrost/ms-teams-deploy-card@2.0.0
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
```
```
(node:5323) UnhandledPromiseRejectionWarning: HttpError: Bad credentials
    at /home/runner/work/_actions/toko-bifrost/ms-teams-deploy-card/2.0.0/dist/index.js:1:346045
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async p (/home/runner/work/_actions/toko-bifrost/ms-teams-deploy-card/2.0.0/dist/index.js:1:343387)
(node:5323) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5323) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

However I'm using the very same github token credentials right above this in another task to post to slack as well, with no issue.

**Comment by aldwyn-acn** [comment]
Hi @Kampe,

Please do not use any secrets with the `GITHUB_` prefix, as it is reserved to be used by Github Actions only. Let me know how it goes.

**Comment by Kampe** [comment]
I'm not, this is the generic github token provided by github actions environment.

**Comment by aldwyn-acn** [comment]
@Kampe, have you set it on your https://github.com/<owner>/<repo>/settings/secrets?

**Comment by Kampe** [comment]
I have a github access token, it's stored as a secret called GH_TOKEN, I am not using that secret here, I am using the default GITHUB_TOKEN and the action does not work.

**Comment by aldwyn-acn** [comment]
Kindly refer [here](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables) for all the available environment variables within the Github Actions workflow.

And here's the [naming convention](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#naming-conventions-for-environment-variables).

There is no default GITHUB_TOKEN. You have to set it manually on your secrets. And if you have set the secret key as `GH_TOKEN `, your yaml should look like this:
```yaml
    - name: Notify dedicated teams channel
      uses: toko-bifrost/ms-teams-deploy-card@2.0.0
      env:
        github-token: ${{ secrets.GH_TOKEN }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
```

**Comment by Kampe** [comment]
Why do you need my github actions token?  I will not use this if you require that level of privileges to run a github action...  Default `GITHUB_TOKEN` would work fine for what this needs, as your action should only be operating on *the repo running the workflow*

**Comment by aldwyn-acn** [comment]
Hi @Kampe,

Apologies, as I wasn't aware of the built-in `GITHUB_TOKEN` because I was looking at a not-so-new Github Actions reference while developing this. Yes, you can use that as well. I even used it in this repository just now and our private enterprise repository, and it just worked. And yes, this action only needs a read-access of the current repo, nothing more.

See the latest run here: https://github.com/toko-bifrost/ms-teams-deploy-card/actions/runs/48810789/workflow.

Maybe your problem is [this](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token):
> GitHub Actions is available with GitHub Free, GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub One. GitHub Actions is not available for private repositories owned by accounts using legacy per-repository plans. For more information, see "GitHub's products."


I'll be updating the README.md. Thanks for the heads-up.

**Comment by aldwyn-acn** [comment]
I have updated the README regarding this issue. Kindly check.

**Comment by Kampe** [comment]
I see the read me and it looks correct, however my action is still failing even using the new version:
```
      - name: 'Publish Message to Teams'
        uses: toko-bifrost/ms-teams-deploy-card@2.1.2
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        if: always()
```

**Comment by aldwyn-acn** [comment]
Hi @Kampe, as per this [comment in a related issue](https://github.com/JamesIves/github-pages-deploy-action/issues/56#issuecomment-555812315), the param `env` should be `with`.

**Comment by aldwyn-acn** [comment]
Hi @Kampe,  when using an action, it should use `with`, not `env`.

**Comment by Kampe** [comment]
Thanks that fixed it!
